### ISSUE TITLE
Constructors in lexer and ast module have different style of initializing char *, with or w/o malloc.

### ISSUE THREAD

**Issue by alex216** [rask24/minishell#38]

**Comment by alex216** [comment]
`token/constructor.c`
`ast/constructor.c`
and
`env/constructor.c`
in the future.

**Comment by rask24** [comment]
In the current implementation, constructors follow a standardized design where all necessary memory is allocated within them. But `construct_lexer` stands out as different.

This is because the lexer module is not just an interface providing utility functions for another module, but rather a module with its own role of generating token sequences. In this context, there is no corresponding data type for the lexer itself. So the name 'construct_lexer' somewhat misleading.

Given that this function actually creates an auxiliary structure for the lexer (and is only used within the lexer function), it would be more appropriate to either

1. Make it static within lexer.c
2. Rename it to something like construct_lexer_info to better reflect its actual purpose.
